level_0 = {
    'node_pos': (145, 155),
    'node_graphic': 'graphics/overworld/level__0.png',
    'terrain': 'levels/0/level_0_terrain.csv',
    'jump_pads': 'levels/0/level_0_jump_pads.csv',
    'player': 'levels/0/level_0_player.csv',
    'coins': 'levels/0/level_0_coins.csv',
    'keys': 'levels/0/level_0_keys.csv',
    'torches': 'levels/0/level_0_torches.csv',
    'spikes': 'levels/0/level_0_spikes.csv',
    'constraints': 'levels/0/level_0_constraints.csv',
    'fake_goal': 'levels/0/level_0_fake_goal.csv',
    'fake_goal1': 'levels/0/level_0_fake_goal1.csv',
    'unlock': 1,
}
level_1 = {
    'node_pos': (355, 155),
    'node_graphic': 'graphics/overworld/level__1.png',
    'terrain': 'levels/1/level_1_terrain.csv',
    'jump_pads': 'levels/1/level_1_jump_pads.csv',
    'player': 'levels/1/level_1_player.csv',
    'coins': 'levels/1/level_1_coins.csv',
    'keys': 'levels/1/level_1_keys.csv',
    'torches': 'levels/1/level_1_torches.csv',
    'spikes': 'levels/1/level_1_spikes.csv',
    'constraints': 'levels/1/level_1_constraints.csv',
    'fake_goal': 'levels/1/level_1_fake_goal.csv',
    'fake_goal1': 'levels/1/level_1_fake_goal1.csv',
    'unlock': 2,
}
level_2 = {
    'node_pos': (145, 264),
    'node_graphic': 'graphics/overworld/level__2.png',
    'terrain': 'levels/2/level_2_terrain.csv',
    'jump_pads': 'levels/2/level_2_jump_pads.csv',
    'player': 'levels/2/level_2_player.csv',
    'coins': 'levels/2/level_2_coins.csv',
    'keys': 'levels/2/level_2_keys.csv',
    'torches': 'levels/2/level_2_torches.csv',
    'spikes': 'levels/2/level_2_spikes.csv',
    'constraints': 'levels/2/level_2_constraints.csv',
    'fake_goal': 'levels/2/level_2_fake_goal.csv',
    'fake_goal1': 'levels/2/level_2_fake_goal1.csv',
    'unlock': 3,
}
level_3 = {
    'node_pos': (355, 264),
    'node_graphic': 'graphics/overworld/level__3.png',
    'terrain': 'levels/3/level_3_terrain.csv',
    'jump_pads': 'levels/3/level_3_jump_pads.csv',
    'player': 'levels/3/level_3_player.csv',
    'coins': 'levels/3/level_3_coins.csv',
    'keys': 'levels/3/level_3_keys.csv',
    'torches': 'levels/3/level_3_torches.csv',
    'spikes': 'levels/3/level_3_spikes.csv',
    'constraints': 'levels/3/level_3_constraints.csv',
    'fake_goal': 'levels/3/level_3_fake_goal.csv',
    'fake_goal1': 'levels/3/level_3_fake_goal1.csv',
    'unlock': 4,
}
level_4 = {
    'node_pos': (245, 373),
    'node_graphic': 'graphics/overworld/level__4.png',
    'terrain': 'levels/4/level_4_terrain.csv',
    'jump_pads': 'levels/4/level_4_jump_pads.csv',
    'player': 'levels/4/level_4_player.csv',
    'coins': 'levels/4/level_4_coins.csv',
    'keys': 'levels/4/level_4_keys.csv',
    'torches': 'levels/4/level_4_torches.csv',
    'spikes': 'levels/4/level_4_spikes.csv',
    'constraints': 'levels/4/level_4_constraints.csv',
    'fake_goal': 'levels/4/level_4_fake_goal.csv',
    'fake_goal1': 'levels/4/level_4_fake_goal1.csv',
    'unlock': 5,
}
level_5 = {
    'node_pos': (245, 479),
    'node_graphic': 'graphics/overworld/level__5.png',
    'terrain': 'levels/5/level_5_terrain.csv',
    'jump_pads': 'levels/5/level_5_jump_pads.csv',
    'player': 'levels/5/level_5_player.csv',
    'coins': 'levels/5/level_5_coins.csv',
    'keys': 'levels/5/level_5_keys.csv',
    'torches': 'levels/5/level_5_torches.csv',
    'spikes': 'levels/5/level_5_spikes.csv',
    'constraints': 'levels/5/level_5_constraints.csv',
    'fake_goal': 'levels/5/level_5_fake_goal.csv',
    'fake_goal1': 'levels/5/level_5_fake_goal1.csv',
    'unlock': 5,
}



levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5,
}
